// Generated by scripts/sync-card-art.mjs. Do not edit by hand.
// Maps a card id to its art file under public/brand/cards.
export const cardArt: Record<string, string> = {
  "luke-runner": "/brand/cards/luke-runner.png",
  "moeda": "/brand/cards/moeda.png"
};
